### PR TITLE
Bug Fixed (2016-02-22)

### PR DESCRIPTION
**Pull request by whitearies**
1.TeamPlay Mode fixed(almost,it is available and could be over and get results, however the round flag is always show "Round 1")
2.Identify some unknown data package struct.
3.Found some unknown data packages.(But still can not analysis them)
4.Confirm that config.ini loader is broken.(Will be fixed later)

### CODE REVIEW

**Comment by Cleroth** [comment]
This can't be merged because of conflicts. You'll have to merge cleroth/master into yours before continuing.
And config.ini works for me.

**Comment by whitearies** [comment]
I have tried to change the config.ini and output it, and the output show that value didn't change, it follows the default value.

**Comment by Cleroth** [comment]
The .exe loads the config one folder up. So if you got `C:/channel/channel.exe`, the ini needs to be in `C:/config.ini`

**Comment by whitearies** [comment]
Got it. I'll try to move the number of rooms setting and other game settings into config.ini, that will be good to control game category, such as "Lucky Day"(Double equipments upgrade success ratio), “Fire Week”(Fire Equipments could be more easier to generate good skills).

**Comment by Cleroth** [comment]
ini is a pretty obsolete format for data representation. I could change the configs to JSON if you want.

**Comment by whitearies** [comment]
Great, I'm in favour of that.

**Comment by Cleroth** [comment]
You really need to update your fork (whitearies:master) with this one though (Cleroth:master). Do you know how to do that or do you need help?

**Pull request closed without merging**
