### PR TITLE
It seems I change too many codes……

### PR DESCRIPTION
**Pull request by whitearies**
1.Shop gold/silver force charge fixed
2.Shop buy package fixed
3.Character can be changed while starting game now, and it is available to change default character now.
4.Skill Fusion,Level Fusion,Skill 1 Fusion,Skill 2 Fusion,Skill 2-1 Fusion, Skill 2-2 Fusion is available now.(Skill 1-1 is too troublesome so fix it later)
5.Card Slot is available and should not be stucked now, but every time you use one cart slot,remember to logout and login again.(Because the response packet is not perfect yet)

I have merge the Shop Elements Card fix.
I wrote a DEBUG define to save the output words into D:\packets.txt

### CODE REVIEW

**Comment by KuizW9** [comment]
Will the trading system complete?

**Comment by whitearies** [comment]
That will be fixed later

**Comment by Cleroth** [comment]
There are conflicts again.

**Comment by whitearies** [comment]
I'd like to create a new branch tu push my code

**Comment by Cleroth** [comment]
You have to merge the current branch here to yours.

**Comment by KuizW9** [comment]
As the CreateRoomResponse 
Would you please get the Value of struct all from Clients Side ? 
Like this ...
CreateRoomRequest.allowcritsheild = CreateRoomRequest->allowcritsheild ;
Since normally the value of room setting is standby the client side when creating room

**Comment by whitearies** [comment]
I'd wrote Skill Fusion,Level Fusion,Skill 1 Fusion,Skill 2 Fusion,Skill 2-1 Fusion, Skill 2-2 Fusion today

**Comment by whitearies** [comment]
Can we make a rule that everyone use space indent but not tabs?
There are so many conflicts looks the same, the only  different is the indents.

**Comment by Cleroth** [comment]
Yea, I noticed the indentation problems is becoming a mess.
I personally hate spaces, since they just increase file size for no reason when you could just be using tabs. Both of you actually converted spaces to tabs though. So how about we agree to use 4-spaced tabs instead? We just really need to run auto format on all the files though.
However, part the problem here is that most of you are editing large parts of code and doing multiple fixes in one go. You would have less conflicts if you committed and pushed the changes instantly, as well as pulling from origin before you create a pull request.

**Comment by tsuncp** [comment]
Personally, I use Ctrl K + Ctrl D to auto format code.

**Comment by Cleroth** [comment]
That's the problem. You're formatting the entire document with that, not just the code you're writing. If everyone does that and we have different formatting settings, we'll just keep changing the formatting at every commit.

**Comment by tsuncp** [comment]
OK. I will only format my code next time.

**Comment by Cleroth** [comment]
You can do it with CTrl K + Ctrl F. I personally rarely use either, as VS tends to auto-format  and indents as you write, and I mostly just manually format things that it doesn't.

**Comment by Cleroth** [comment]
I formatted all files (using tabs). You should update ASAP.

**Pull request merged**
